#--------------------------------------------------------------
#               K1 Make framework
# Author: Andrea Ravalli (andrea.ravalli@nttdata.com)
#--------------------------------------------------------------

#---------------------
# Source code files
#---------------------
APPLICATION := property-server
SOURCES := property_server.c

SERVICE_IF_LIBS = properties
SERVICE_IF_LIBS_PATH = ../lib-$(ARCH)/
SERVICE_IF_INC_PATH = ../generated/

EXT_IF_LIBS :=
EXT_IF_LIBS_PATH := 
EXT_IF_INC_PATH := 

EXTERNAL_LIBS := 
EXTERNAL_INC_PATH := 
EXTERNAL_LIBS_PATH := 

MKFRW = ../makefrw

include $(MKFRW)/build-targets.mk