#--------------------------------------------------------------
#               K1 Make framework
# Author: Andrea Ravalli (andrea.ravalli@nttdata.com)
#--------------------------------------------------------------


MKFRW = ../makefrw
include $(MKFRW)/functions.mk 

#---------------------
# User input interfaces definitions (.xml, .conf, .service)
#---------------------

INTERFACE_SPECS := org.softcoredesign.properties.Test.xml

CONFIG_FILES := org.softcoredesign.properties.Test.conf

SERVICE_FILES := 

IF_PREFIX := org.softcoredesign.properties

GEN_DIR := ../generated

PREFIX := .

include $(MKFRW)/interfaces.mk
